### ISSUE TITLE
쓰레드 페이지 갯수에 오류있음

### ISSUE THREAD

**Issue by 5hyunseok** [5hyunseok/project-euler-kr#12]
각 문제에 대한 쓰레드 갯수와 페이지개수가 아니라
전체로 나옴

**Comment by 5hyunseok** [comment]
![image](https://user-images.githubusercontent.com/28381616/47335281-77b43400-d6c5-11e8-9cf4-a8dc4515b651.png)

**Comment by 5hyunseok** [comment]
![image](https://user-images.githubusercontent.com/28381616/47335295-8a2e6d80-d6c5-11e8-96f2-30d5a5e1ce3d.png)

문제번호 3이랑 2일 때 결과

**Comment by eastop716** [comment]
아 그럼 번역 게시판도 같은 문제 있음
이거 2개 api 수정하겟음

**Comment by eastop716** [comment]
수정댐
