### ISSUE TITLE
포스트 몇가지 수정해야할 것

### ISSUE THREAD

**Issue by 5hyunseok** [5hyunseok/project-euler-kr#17]
1. 수정할 때 카테고리 설정안되게

2. 문제번호 체크하기 (있는 문제인지)

**Comment by 5hyunseok** [comment]
2. 문제번호 체크하는거 프론트에서 하지말고 그냥 서버에서 submit 했을때 문제번호 foreign key constraint 어겨지면 특정 코드나 에러메세지 주는걸로 하자 @eastop716

**Comment by eastop716** [comment]
mevn브랜치에 푸시됨 api doc 보면 
1번은 그냥 카테고리 안받고
2번은 문제번호 체크해서 에러메시지 날림

**Comment by 5hyunseok** [comment]
해결
