### ISSUE TITLE
번역 채택됐을때

### ISSUE THREAD

**Issue by 5hyunseok** [5hyunseok/project-euler-kr#19]
포스트에 '채택됨' 같은 태그 달아주기

문제에 번역자, 오역/오타 찾은사람 같이 반환해주기

**Comment by 5hyunseok** [comment]
태그는 필요없고 걍 댓글 달아줘도 되겠다

**Comment by 5hyunseok** [comment]
아니면 해결됨 같은 태그가 있어도될듯

**Comment by eastop716** [comment]
problems - Get a Problem
문제에 번역자, 오역 오타 찾은사람 추가됨 

근데 관리자 모드가 없어서 디비로 직접 추가해야댐

**Comment by 5hyunseok** [comment]
해결
