### ISSUE TITLE
번역 게시판 API

### ISSUE THREAD

**Issue by eastop716** [5hyunseok/project-euler-kr#7]
- 게시판 불러오기
페이지별로 20개 
번역 제목, 번역 내용, 유저 정보

- 자기 번역  지우기 

- 자기  번역 업데이트

- 총 갯수, 총 페이지 갯수 불러오기

- 번역 업로드

**Comment by 5hyunseok** [comment]
이거에 오역 추가하자
번역/오역 게시판

**Comment by eastop716** [comment]
으어어어어어어 translate submit 하는 api url 바뀜 통합하느라
/api/problems/:id/translate -> /api/problems/:id/translates 
맨뒤에 s 추가됨
